import type { Program, ProgramDay, ProgramWeek, Scheme, Slot } from '../types'

/**
 * The 12-week programs, built as typed content. Weeks are generated by small
 * builders so the structure stays readable; the emitted object is plain data
 * the engine consumes. Human-readable versions live in docs/programs/.
 */

/* ================= Golf Athlete 5/3/1 (intermediate) =================
 * Leader 1 (wks 1-3, 5s PRO + FSL) · deload wk 4 · Leader 2 (wks 5-7) ·
 * deload wk 8 · Anchor (wks 9-11, PR sets capped at RPE 9 + 3×5 FSL) ·
 * wk 12 TM test. Every session opens with mobility + jumps/throws.
 */

const RPE_CAP = 9

type WavePct = Array<{ pct: number; reps: number; amrap?: boolean }>

/** 5s PRO leader waves — straight fives, no grinding. */
const LEADER_WAVES: WavePct[] = [
  [{ pct: 0.65, reps: 5 }, { pct: 0.75, reps: 5 }, { pct: 0.85, reps: 5 }],
  [{ pct: 0.7, reps: 5 }, { pct: 0.8, reps: 5 }, { pct: 0.9, reps: 5 }],
  [{ pct: 0.75, reps: 5 }, { pct: 0.85, reps: 5 }, { pct: 0.95, reps: 5 }],
]

/** Anchor waves — classic 5/3/1 with a PR (AMRAP) top set. */
const ANCHOR_WAVES: WavePct[] = [
  [{ pct: 0.65, reps: 5 }, { pct: 0.75, reps: 5 }, { pct: 0.85, reps: 5, amrap: true }],
  [{ pct: 0.7, reps: 3 }, { pct: 0.8, reps: 3 }, { pct: 0.9, reps: 3, amrap: true }],
  [{ pct: 0.75, reps: 5 }, { pct: 0.85, reps: 3 }, { pct: 0.95, reps: 1, amrap: true }],
]

const DELOAD_WAVE: WavePct = [
  { pct: 0.4, reps: 5 },
  { pct: 0.5, reps: 5 },
  { pct: 0.6, reps: 5 },
]

function main531(liftKey: string, wave: WavePct, withCap = false): Scheme {
  return { kind: 'percentTM', liftKey, sets: wave, ...(withCap ? { rpeCap: RPE_CAP } : {}) }
}

/** First-Set-Last supplemental volume: sets×5 at the wave's first percentage. */
function fsl(liftKey: string, wave: WavePct, sets: number): Scheme {
  return {
    kind: 'percentTM',
    liftKey,
    sets: Array.from({ length: sets }, () => ({ pct: wave[0].pct, reps: 5 })),
  }
}

function fixed(sets: number, reps: number, extra?: Partial<Extract<Scheme, { kind: 'fixedSets' }>>): Scheme {
  return { kind: 'fixedSets', sets, reps, ...extra }
}

function dp(sets: number, repMin: number, repMax: number, startLbs: number, incrementLbs = 5): Scheme {
  return { kind: 'doubleProgression', sets, repMin, repMax, startLbs, incrementLbs }
}

const LOWER_PRIMER = ['90/90 hip switch × 8/side', 'Open book × 6/side', 'Leg swings × 10/side']
const UPPER_PRIMER = ['Open book × 6/side', 'Band pull-apart × 15', 'Shoulder CARs × 5/side']
const POWER_PRIMER = ["World's greatest stretch × 4/side", 'Hip airplane × 5/side', 'Deep squat hold 45s']

interface AthleteWeekOpts {
  wave: WavePct
  anchor: boolean
  deload: boolean
  /** anchor block alternates top-set emphasis between squat and trap-bar DL */
  dlEmphasis?: boolean
}

function athleteWeek(week: number, label: string, opts: AthleteWeekOpts): ProgramWeek {
  const { wave, anchor, deload, dlEmphasis } = opts
  const fslSets = deload ? 0 : anchor ? 3 : 5
  const acc = (slots: Slot[]): Slot[] => (deload ? slots.filter((s) => !s.id.endsWith('-acc')) : slots)

  const lowerMainLift = dlEmphasis ? 'deadlift' : 'squat'
  const lowerMainEx = dlEmphasis ? 'trap-bar-deadlift' : 'back-squat'
  const lowerFslLift = dlEmphasis ? 'squat' : 'deadlift'
  const lowerFslEx = dlEmphasis ? 'back-squat' : 'trap-bar-deadlift'

  const day1: ProgramDay = {
    day: 1,
    name: dlEmphasis ? 'Lower — Pull' : 'Lower — Squat',
    primer: LOWER_PRIMER,
    slots: acc([
      { id: 'd1-jump', exerciseId: 'trap-bar-jump', scheme: fixed(deload ? 3 : 5, 3, { note: 'Max intent. Full rest. Light load.' }), restSec: 90 },
      { id: 'd1-main', exerciseId: lowerMainEx, scheme: main531(lowerMainLift, wave, anchor), restSec: 300, heavyLower: true, golfAlternate: { exerciseId: 'banded-hinge', scheme: fixed(3, 8, { note: 'Fast hips, easy on recovery — round tomorrow.' }) } },
      ...(fslSets > 0
        ? [{ id: 'd1-fsl', exerciseId: lowerFslEx, scheme: fsl(lowerFslLift, wave, fslSets), restSec: 180, heavyLower: true, golfAlternate: { exerciseId: 'glute-bridge', scheme: fixed(3, 12) } } satisfies Slot]
        : []),
      { id: 'd1-split-acc', exerciseId: 'bulgarian-split-squat', scheme: dp(3, 8, 12, 40), restSec: 120 },
      { id: 'd1-ham-acc', exerciseId: 'nordic-curl', scheme: fixed(3, 4, { note: 'Assist with hands as needed. Slowest possible negative.' }), restSec: 120 },
      { id: 'd1-core-acc', exerciseId: 'half-kneeling-pallof', scheme: fixed(3, 10, { perSide: true }), restSec: 60 },
    ]),
  }

  const day2: ProgramDay = {
    day: 2,
    name: 'Upper — Bench',
    primer: UPPER_PRIMER,
    slots: acc([
      { id: 'd2-throw', exerciseId: 'mb-chest-pass', scheme: fixed(deload ? 2 : 3, 5, { note: 'Throw hard. This is speed work, not cardio.' }), restSec: 90 },
      { id: 'd2-main', exerciseId: 'bench-press', scheme: main531('bench', wave, anchor), restSec: 300 },
      ...(fslSets > 0 ? [{ id: 'd2-fsl', exerciseId: 'bench-press', scheme: fsl('bench', wave, fslSets), restSec: 180 } satisfies Slot] : []),
      { id: 'd2-chin-acc', exerciseId: 'chin-up', scheme: dp(3, 6, 10, 0, 5), supersetGroup: 'A', restSec: 120 },
      { id: 'd2-row-acc', exerciseId: 'one-arm-db-row', scheme: dp(3, 8, 12, 60), supersetGroup: 'A', restSec: 120 },
      { id: 'd2-face-acc', exerciseId: 'band-face-pull', scheme: fixed(3, 15), restSec: 60 },
      { id: 'd2-carry-acc', exerciseId: 'suitcase-carry', scheme: fixed(3, 1, { perSide: true, note: '40 m per side, heavy. Stand tall.' }), restSec: 90 },
    ]),
  }

  const day3: ProgramDay = {
    day: 3,
    name: 'Golf Power',
    primer: POWER_PRIMER,
    slots: [
      { id: 'd3-scoop', exerciseId: 'mb-rotational-scoop-toss', scheme: fixed(deload ? 2 : 4, 3, { perSide: true, note: 'Full speed. Stop the set if speed drops.' }), restSec: 120 },
      { id: 'd3-step', exerciseId: 'mb-step-behind-throw', scheme: fixed(deload ? 2 : 3, 3, { perSide: true }), restSec: 120 },
      { id: 'd3-broad', exerciseId: 'broad-jump', scheme: fixed(3, 3, { note: 'Stick every landing.' }), restSec: 120 },
      { id: 'd3-bound', exerciseId: 'lateral-bound', scheme: fixed(3, 3, { perSide: true }), restSec: 90 },
      { id: 'd3-chop', exerciseId: 'band-chop', scheme: fixed(3, 8, { perSide: true }), restSec: 60 },
      { id: 'd3-z2', exerciseId: 'treadmill-zone2', scheme: { kind: 'timeDistance', minutes: 25, zone: 'z2', note: 'Optional finisher — skip if short on time.' }, restSec: 0 },
    ],
  }

  const day4: ProgramDay = {
    day: 4,
    name: 'Press + Arms',
    primer: UPPER_PRIMER,
    slots: acc([
      { id: 'd4-slam', exerciseId: 'mb-overhead-slam', scheme: fixed(deload ? 2 : 3, 5, { note: 'Full-body snap. Throw through the floor.' }), restSec: 90 },
      { id: 'd4-main', exerciseId: 'overhead-press', scheme: main531('press', wave, anchor), restSec: 300 },
      ...(fslSets > 0 ? [{ id: 'd4-fsl', exerciseId: 'overhead-press', scheme: fsl('press', wave, fslSets), restSec: 180 } satisfies Slot] : []),
      { id: 'd4-dip-acc', exerciseId: 'dips', scheme: dp(3, 8, 12, 0, 5), supersetGroup: 'A', restSec: 120 },
      { id: 'd4-pull-acc', exerciseId: 'pull-up', scheme: dp(3, 6, 10, 0, 5), supersetGroup: 'A', restSec: 120 },
      { id: 'd4-curl-acc', exerciseId: 'barbell-curl', scheme: dp(3, 8, 12, 45), restSec: 90 },
      { id: 'd4-cuff-acc', exerciseId: 'band-external-rotation', scheme: fixed(2, 12, { perSide: true }), restSec: 45 },
    ]),
  }

  return { week, label, deload: deload || undefined, days: [day1, day2, day3, day4] }
}

function tmTestWeek(week: number): ProgramWeek {
  const testDay = (day: number, name: string, liftKey: string, exerciseId: string, extras: Slot[]): ProgramDay => ({
    day,
    name,
    primer: day === 1 ? LOWER_PRIMER : UPPER_PRIMER,
    slots: [
      { id: `d${day}-test`, exerciseId, scheme: { kind: 'tmTest', liftKey }, restSec: 300 },
      ...extras,
    ],
  })
  return {
    week,
    label: 'Test week — prove the block',
    days: [
      testDay(1, 'Test — Squat + Pull', 'squat', 'back-squat', [
        { id: 'd1-test2', exerciseId: 'trap-bar-deadlift', scheme: { kind: 'tmTest', liftKey: 'deadlift' }, restSec: 300 },
      ]),
      testDay(2, 'Test — Bench', 'bench', 'bench-press', [
        { id: 'd2-chin', exerciseId: 'chin-up', scheme: fixed(3, 5), restSec: 120 },
      ]),
      {
        day: 3,
        name: 'Golf Power — light',
        primer: POWER_PRIMER,
        slots: [
          { id: 'd3-scoop', exerciseId: 'mb-rotational-scoop-toss', scheme: fixed(3, 3, { perSide: true }), restSec: 120 },
          { id: 'd3-broad', exerciseId: 'broad-jump', scheme: fixed(2, 3), restSec: 120 },
          { id: 'd3-z2', exerciseId: 'treadmill-zone2', scheme: { kind: 'timeDistance', minutes: 30, zone: 'z2' }, restSec: 0 },
        ],
      },
      testDay(4, 'Test — Press', 'press', 'overhead-press', [
        { id: 'd4-dip', exerciseId: 'dips', scheme: fixed(3, 8), restSec: 120 },
      ]),
    ],
  }
}

export const golfAthlete531: Program = {
  id: 'golf-athlete-531',
  name: 'Golf Athlete 5/3/1',
  tagline: '12 weeks · 4 days · strength that shows up on the tee',
  description:
    'Wendler 5/3/1 run as Leader → Leader → Anchor across 12 weeks, with the golf research built in: every session opens with mobility and max-intent jumps or throws (jump impulse is the strongest clubhead-speed correlate), trap-bar and split-squat work builds ground force, and a dedicated Golf Power day keeps rotational speed sharp. Leaders use 5s PRO + First-Set-Last volume — no grinding. The Anchor brings capped PR sets, and week 12 tests your new training maxes.',
  level: 'intermediate',
  daysPerWeek: 4,
  lifts: [
    { key: 'squat', exerciseId: 'back-squat', tmIncrementLbs: 10 },
    { key: 'bench', exerciseId: 'bench-press', tmIncrementLbs: 5 },
    { key: 'deadlift', exerciseId: 'trap-bar-deadlift', tmIncrementLbs: 10 },
    { key: 'press', exerciseId: 'overhead-press', tmIncrementLbs: 5 },
  ],
  weeks: [
    athleteWeek(1, 'Leader 1 · 5s PRO + 5×5 FSL', { wave: LEADER_WAVES[0], anchor: false, deload: false }),
    athleteWeek(2, 'Leader 1 · 5s PRO + 5×5 FSL', { wave: LEADER_WAVES[1], anchor: false, deload: false }),
    athleteWeek(3, 'Leader 1 · 5s PRO + 5×5 FSL', { wave: LEADER_WAVES[2], anchor: false, deload: false }),
    athleteWeek(4, 'Deload — easy on purpose', { wave: DELOAD_WAVE, anchor: false, deload: true }),
    athleteWeek(5, 'Leader 2 · 5s PRO + 5×5 FSL', { wave: LEADER_WAVES[0], anchor: false, deload: false }),
    athleteWeek(6, 'Leader 2 · 5s PRO + 5×5 FSL', { wave: LEADER_WAVES[1], anchor: false, deload: false }),
    athleteWeek(7, 'Leader 2 · 5s PRO + 5×5 FSL', { wave: LEADER_WAVES[2], anchor: false, deload: false }),
    athleteWeek(8, 'Deload — recharge for the Anchor', { wave: DELOAD_WAVE, anchor: false, deload: true }),
    athleteWeek(9, 'Anchor · PR sets, cap RPE 9', { wave: ANCHOR_WAVES[0], anchor: true, deload: false }),
    athleteWeek(10, 'Anchor · PR sets, cap RPE 9', { wave: ANCHOR_WAVES[1], anchor: true, deload: false, dlEmphasis: true }),
    athleteWeek(11, 'Anchor · PR sets, cap RPE 9', { wave: ANCHOR_WAVES[2], anchor: true, deload: false }),
    tmTestWeek(12),
  ],
}

/* ================= Foundations (novice, 3 days) =================
 * Weeks 1-2: technique — groove the barbell patterns light.
 * Weeks 3-12: GZCLP rotation (A1 B1 A2 / B2 A1 B1 / ...), T3 double
 * progression, golf touch on day 3, encouragement built into the copy.
 */

const FOUNDATION_PRIMER = ['Cat-cow × 8', '90/90 hip switch × 6/side', 'Band lateral walk × 10/side']

const T1_STAGES = [
  { sets: 5, reps: 3, amrapLast: true },
  { sets: 6, reps: 2, amrapLast: true },
  { sets: 10, reps: 1, amrapLast: true },
]
const T2_STAGES = [
  { sets: 3, reps: 10, amrapLast: false },
  { sets: 3, reps: 8, amrapLast: false },
  { sets: 3, reps: 6, amrapLast: false },
]

function t1(liftKey: string): Scheme {
  return { kind: 'linearStages', liftKey, stages: T1_STAGES, incrementLbs: liftKey === 'bench' || liftKey === 'press' ? 5 : 10 }
}
function t2(liftKey: string): Scheme {
  return { kind: 'linearStages', liftKey: liftKey + '-t2', stages: T2_STAGES, incrementLbs: 5 }
}

interface GzclpTemplate {
  name: string
  t1Lift: string
  t1Ex: string
  t2Lift: string
  t2Ex: string
  t3: Slot[]
}

const GZCLP_DAYS: GzclpTemplate[] = [
  {
    name: 'A1 — Squat focus',
    t1Lift: 'squat', t1Ex: 'back-squat',
    t2Lift: 'bench', t2Ex: 'bench-press',
    t3: [
      { id: 't3-row', exerciseId: 'one-arm-db-row', scheme: dp(3, 10, 15, 20), restSec: 90 },
      { id: 't3-core', exerciseId: 'dead-bug', scheme: fixed(3, 8, { perSide: true }), restSec: 60 },
    ],
  },
  {
    name: 'B1 — Press focus',
    t1Lift: 'press', t1Ex: 'overhead-press',
    t2Lift: 'deadlift', t2Ex: 'trap-bar-deadlift',
    t3: [
      { id: 't3-hip', exerciseId: 'db-hip-thrust', scheme: dp(3, 10, 15, 25), restSec: 90 },
      { id: 't3-side', exerciseId: 'side-plank', scheme: fixed(3, 1, { perSide: true, note: 'Hold 20-40s per side. Quality over clock.' }), restSec: 60 },
    ],
  },
  {
    name: 'A2 — Bench focus',
    t1Lift: 'bench', t1Ex: 'bench-press',
    t2Lift: 'squat', t2Ex: 'back-squat',
    t3: [
      { id: 't3-chin', exerciseId: 'band-assisted-chin-up', scheme: dp(3, 5, 8, 0, 0), restSec: 90 },
      { id: 't3-pallof', exerciseId: 'pallof-press', scheme: fixed(3, 10, { perSide: true }), restSec: 60 },
    ],
  },
  {
    name: 'B2 — Deadlift focus',
    t1Lift: 'deadlift', t1Ex: 'trap-bar-deadlift',
    t2Lift: 'press', t2Ex: 'overhead-press',
    t3: [
      { id: 't3-scoop', exerciseId: 'mb-rotational-scoop-toss', scheme: fixed(3, 3, { perSide: true, note: 'Throw it like you mean it — this is your golf speed.' }), restSec: 90 },
      { id: 't3-pull', exerciseId: 'band-pull-apart', scheme: fixed(3, 15), restSec: 60 },
    ],
  },
]

function gzclpDay(dayNum: number, template: GzclpTemplate): ProgramDay {
  return {
    day: dayNum,
    name: template.name,
    primer: FOUNDATION_PRIMER,
    slots: [
      { id: `t1-${template.t1Lift}`, exerciseId: template.t1Ex, scheme: t1(template.t1Lift), restSec: 180, heavyLower: template.t1Lift === 'squat' || template.t1Lift === 'deadlift', golfAlternate: { exerciseId: 'glute-bridge', scheme: fixed(3, 12, { note: 'Light day — round tomorrow.' }) } },
      { id: `t2-${template.t2Lift}`, exerciseId: template.t2Ex, scheme: t2(template.t2Lift), restSec: 120 },
      ...template.t3,
    ],
  }
}

function techniqueWeek(week: number): ProgramWeek {
  const day = (dayNum: number, name: string, slots: Slot[]): ProgramDay => ({
    day: dayNum,
    name,
    primer: FOUNDATION_PRIMER,
    slots,
  })
  const note = 'Empty bar or light. You are grooving the pattern, not chasing weight — that comes soon.'
  return {
    week,
    label: 'Technique — light on purpose, momentum stays',
    days: [
      day(1, 'Full Body A + squat practice', [
        { id: 'tech-squat', exerciseId: 'back-squat', scheme: fixed(3, 5, { loadLbs: 45, note }), restSec: 120 },
        { id: 'gob', exerciseId: 'goblet-squat', scheme: dp(3, 8, 12, 25), restSec: 90 },
        { id: 'dbb', exerciseId: 'db-bench-press', scheme: dp(3, 8, 12, 30), restSec: 90 },
        { id: 'row', exerciseId: 'one-arm-db-row', scheme: dp(3, 10, 12, 20), restSec: 90 },
        { id: 'plank', exerciseId: 'plank', scheme: fixed(3, 1, { note: 'Hold 25-45s. Straight line, strong breath.' }), restSec: 60 },
      ]),
      day(2, 'Full Body B + press practice', [
        { id: 'tech-press', exerciseId: 'overhead-press', scheme: fixed(3, 5, { loadLbs: 45, note }), restSec: 120 },
        { id: 'lunge', exerciseId: 'db-reverse-lunge', scheme: dp(3, 8, 10, 15), restSec: 90 },
        { id: 'rdl', exerciseId: 'db-rdl', scheme: dp(3, 10, 12, 40), restSec: 90 },
        { id: 'csrow', exerciseId: 'chest-supported-db-row', scheme: dp(3, 10, 12, 20), restSec: 90 },
        { id: 'bug', exerciseId: 'dead-bug', scheme: fixed(3, 8, { perSide: true }), restSec: 60 },
      ]),
      day(3, 'Full Body C + hinge practice', [
        { id: 'tech-dl', exerciseId: 'trap-bar-deadlift', scheme: fixed(3, 5, { loadLbs: 65, note }), restSec: 120 },
        { id: 'hip', exerciseId: 'db-hip-thrust', scheme: dp(3, 10, 15, 25), restSec: 90 },
        { id: 'incl', exerciseId: 'incline-db-press', scheme: dp(3, 8, 12, 25), restSec: 90 },
        { id: 'scoop', exerciseId: 'mb-rotational-scoop-toss', scheme: fixed(3, 3, { perSide: true, note: 'Light ball, big speed. Golf power starts here.' }), restSec: 90 },
        { id: 'side', exerciseId: 'side-plank', scheme: fixed(2, 1, { perSide: true, note: 'Hold 15-30s per side.' }), restSec: 60 },
      ]),
    ],
  }
}

function gzclpWeek(week: number): ProgramWeek {
  // Rotation continues across weeks: wk3 = A1 B1 A2, wk4 = B2 A1 B1, ...
  const startIndex = (week - 3) * 3
  const days: ProgramDay[] = [0, 1, 2].map((i) => gzclpDay(i + 1, GZCLP_DAYS[(startIndex + i) % 4]))
  return { week, label: `GZCLP · ${days.map((d) => d.name.split(' ')[0]).join(' ')}`, days }
}

export const foundations: Program = {
  id: 'foundations-gzclp',
  name: 'Foundations',
  tagline: '12 weeks · 3 days · from new-to-barbells to genuinely strong',
  description:
    'Two weeks of light technique work to groove the barbell patterns, then ten weeks of GZCLP — the best-regarded beginner progression there is. Every session has one heavy focus lift, one supporting lift, and accessory work you can push. When a weight stalls, the program changes the rep scheme instead of punishing you — stalls are planned, not failures. Milestones get named along the way: first bodyweight squat, first full push-up, first chin-up.',
  level: 'beginner',
  daysPerWeek: 3,
  lifts: [
    { key: 'squat', exerciseId: 'back-squat', tmIncrementLbs: 0 },
    { key: 'bench', exerciseId: 'bench-press', tmIncrementLbs: 0 },
    { key: 'deadlift', exerciseId: 'trap-bar-deadlift', tmIncrementLbs: 0 },
    { key: 'press', exerciseId: 'overhead-press', tmIncrementLbs: 0 },
  ],
  weeks: [
    techniqueWeek(1),
    techniqueWeek(2),
    ...Array.from({ length: 10 }, (_, i) => gzclpWeek(i + 3)),
  ],
}

export const programs: Program[] = [golfAthlete531, foundations]

export function getProgram(id: string): Program | undefined {
  return programs.find((p) => p.id === id)
}

/** Default starting loads for Foundations linearStages, by liftKey (incl. -t2 keys). */
export const FOUNDATION_DEFAULT_LOADS: Record<string, number> = {
  squat: 45, 'squat-t2': 45,
  bench: 45, 'bench-t2': 45,
  deadlift: 75, 'deadlift-t2': 65,
  press: 45, 'press-t2': 45,
}
